name: Tidy ANZSIC

on:
  push:

jobs:
  tidy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with: 
          python-version: 3.x

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run notebook
        run: papermill tidy.ipynb tidy-rendered.ipynb

      - name: Upload CSV artifact
        uses: actions/upload-artifact@v4
        with:
          name: anzsic_2006.csv
          path: anzsic_2006.csv

